[package]
name = "test-skip-doc-links"
version = "0.1.0"
edition = "2024"

[dependencies]
dep = { path = "./crates/dep" }

[workspace.metadata.insert-docs]
skip-doc-links = ["dep::skipped_by_workspace"]

[package.metadata.insert-docs]
feature-into-crate = false
skip-doc-links = ["dep::skipped_by_package"]
